#!/bin/bash
# Sui Scratch Lottery - Testnet Deployment Guide

echo "=== Sui Scratch Lottery Testnet Deployment ==="
echo ""
echo "✅ STEP 1: SMART CONTRACT DEPLOYED"
echo "   Package ID: 0x54e4ab9a7dfb6fbcf5cd0e99a697f321ee09515634b1b23a6cbfb7a477960b0c"
echo "   Chain ID:   4c78adac (Sui Testnet)"
echo ""
echo "📋 STEP 2: GET LOTTERY OBJECT ID"
echo ""
echo "   Option A: Via Sui Explorer"
echo "   1. Visit: https://suiscan.xyz/testnet/object/0x54e4ab9a7dfb6fbcf5cd0e99a697f321ee09515634b1b23a6cbfb7a477960b0c"
echo "   2. Find the ScratchLottery object in 'Created Objects'"
echo "   3. Copy its Object ID"
echo ""
echo "   Option B: Via CLI (if object was created during init)"
echo "   sui client objects | grep -i scratchlottery"
echo ""
echo "⚙️  STEP 3: UPDATE .env"
echo ""
echo "   VITE_SUI_FRAMEWORK_PACKAGE_ID=0x2"
echo "   VITE_SUI_RANDOM_PACKAGE_ID=0x8"
echo "   VITE_SUI_NETWORK=testnet"
echo "   VITE_SUI_FULLNODE_URL=https://rpc.testnet.sui.io:443"
echo "   VITE_LOTTERY_PACKAGE_ID=0x54e4ab9a7dfb6fbcf5cd0e99a697f321ee09515634b1b23a6cbfb7a477960b0c"
echo "   VITE_LOTTERY_OBJECT_ID=0x<FROM_STEP_2>"
echo ""
echo "🚀 STEP 4: START DEV SERVER"
echo ""
echo "   npm run dev"
echo ""
echo "✨ STEP 5: TEST IN UI"
echo "   1. Connect your Sui testnet wallet"
echo "   2. Buy a scratch ticket"
echo "   3. Scratch the cells"
echo "   4. Claim your prize"
echo ""
echo "📊 VERIFICATION"
echo "   - Check transactions on https://suiscan.xyz/testnet"
echo "   - Verify wallet balance changes after buy/claim"
echo "   - Confirm Randomness module (0x8) was used in buy_scratch_card()"
echo ""
